### ISSUE TITLE
Default to latest BIG-IP release

### ISSUE THREAD

**Issue by codygreen** [f5alliances/f5_provisioner#13]
currently, TMOS 13.1.0.7 is deployed.  We should target the latest version of the BIG-IP AMI.

**Comment by payalsin** [comment]
I would want to leave it at one TMOS release since if we keep supporting the latest we will have to test everything that we are  running on this environment using the latest release. Maybe first phase we go with 13.1.0.7 and then gradually start supporting more BIG-IP releases.

We can provide it to be a variable so that if customer/user wants to install another release they have a path forward

**Comment by ericzji** [comment]
migrated to https://github.com/f5devcentral/FAS-provisioner/issues/5
